### ISSUE TITLE
kubectl Windows Command doesn't work

### ISSUE THREAD

**Issue by mikarnik** [OpenUnison/openunison-k8s-login-activedirectory#66]
I have some windows users and kubectl Windows Command from "Kubernetes Tokens" page doesn't work. There is a missing part with certificate-authority-data. Is it possible to edit the template? I have a working solution. You have to run it in PowerShell. I had to add some commands at the beginning, replace kubectl config set-cluster command and at the end delete the folder with ca. Use `r`n for a new line.

md c:\k8sca -Force ; "-----BEGIN CERTIFICATE-----`r`nMIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl`r`ncm5ldGVzMB4XDTIwMDMz...shorten...xLP56/WE8gmR`r`n6VOpWRphnJ7syM91UUzLV0tjtdvlkrS6U7QRXxSn2SgCclK5mAyH4UdsRWg=`r`n-----END CERTIFICATE-----" | out-file c:\ouca\ca.crt -encoding oem ; kubectl config set-cluster aim-cluster-02 --server=https://cluster.company.local:6443 --certificate-authority=C:\k8sca\ca.crt --embed-certs=true ; ..... this part of windows command is ok ..... ; Remove-Item -recurse -force C:\k8sca

Is it possible to fix it?

**Comment by mlbiam** [comment]
If you are already using the image `docker.io/tremolosecurity/betas:k8s-login-activedirectory-1.0.18` go ahead and delete your pod.  When it starts again the winidows kubectl option will have the cluster certifiicate embedded in it just like the *nix one.  I tweaked your code a bit to use a temp file instead of hardcoding where to put the cert temporarily.  Thanks for the template code, something I wanted to add for a while.

**Comment by mikarnik** [comment]
Thanks, it works great.
