### ISSUE TITLE
Credentials in Plain Text in /auth/formLogin

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#87]
I can see the credentials in plain text from the browser console in the path /auth/formLogin , is it a known issue? They are parsed as clear text in formData

**Comment by mlbiam** [comment]
Can you please provide a screenshot?  I don't know what you mean by being visible in the console as plain text in your browser

**Comment by vbottu** [comment]
in the network tab of browser(developer tools) under request headers there is formdata captured , where I can see the username/passwd in clear text
![image](https://user-images.githubusercontent.com/19859827/119177269-16e66700-ba3a-11eb-98f0-e4ba1b814185.png)

**Comment by mlbiam** [comment]
I see.  This is expected.  It's a simple web form and there's no way to encrypt it at the browser level.  If you do this with any website that collects information (including a username and password), you'll see the same thing.  For instance this is a screen shot from logging into Okta:

![Screenshot from 2021-05-21 13-53-50](https://user-images.githubusercontent.com/8249283/119179226-b0af1380-ba3c-11eb-89d5-a8eda56a2b2f.png)

Same thing, the username and password in clear text.  That's because the browser has to be able submit the credentials without having any kind of pre-estabished trust.
